<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="page-header">
    <h1>
        Search activity
    </h1>
    <p>
        <?php echo $this->tag->linkTo(["activity/new", "Create activity"]) ?>
    </p>
</div>
<?php echo $this->getContent(); ?>

<div class="row">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Activityid</th>
            <th>Activityname</th>
            <th>Activitydescription</th>
            <th>Activitydate</th>
            <th>Activityplace</th>
            <th>Urlpicture</th>

                
            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $activity): ?>
            <tr>
                <td><?php echo $activity->activityid ?></td>
            <td><?php echo $activity->activityname ?></td>
            <td><?php echo $activity->activitydescription ?></td>
            <td><?php echo $activity->activitydate ?></td>
            <td><?php echo $activity->activityplace ?></td>
            
            <td><img src="<?php echo $activity->urlpicture?>"width="250" height="250"></td>

                
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<div class="row">
    <div class="col-sm-1">
        <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
            <?php echo $page->current, "/", $page->total_pages ?>
        </p>
    </div>
    <div class="col-sm-11">
        <nav>
            <ul class="pagination">
                <li><?php echo $this->tag->linkTo("activity/search", "First") ?></li>
                <li><?php echo $this->tag->linkTo("activity/search?page=" . $page->before, "Previous") ?></li>
                <li><?php echo $this->tag->linkTo("activity/search?page=" . $page->next, "Next") ?></li>
                <li><?php echo $this->tag->linkTo("activity/search?page=" . $page->last, "Last") ?></li>
            </ul>
        </nav>
    </div>
</div>